services:
  mobile-banking-api:
    image: "mobile-banking-api"
    build: .
    container_name: mobile-banking-api
    ports:
      - 16800:8080
    volumes:
      - F:/Sem Sopanha/Spring Framework/BankSystem/File Server/:/File Server/
    networks:
      - mobile-banking-net
    restart: always
    depends_on:
      - mobile-banking-db


  mobile-banking-db:
    image: postgres:16.3-bullseye
    container_name: mobile-banking-db
    ports:
      - 4441:5432
    environment:
      POSTGRES_PASSWORD: sbc11@2024
      POSTGRES_USER: sbc11
      POSTGRES_DB: mobile_banking_db
    volumes:
      - mobile-banking-vol:/var/lib/postgresql/data
    networks:
      - mobile-banking-net

volumes:
  mobile-banking-vol:

networks:
  mobile-banking-net:

